#spring:
  #cloud:
    #gateway:
      #routes:
       # - id: r1
        #  uri: http://localhost:9091/
         # predicates:
          # - Path= /customers/**
       # - id: r2
        #  uri: http://localhost:9092/
         # predicates:
          # - Path= /products/**   
